### ISSUE TITLE
'xml' does not exist

### ISSUE THREAD

**Issue by kxhit** [Thinklab-SJTU/PCA-GM#1]
Hi! Thanks for sharing your code!

I met an error when running the code.
Could you help me? Thanks!!!

```
python train_eval.py --cfg experiments/vgg16_pca_voc.yaml 
/media/work/3D/PCA-GM/utils/config.py:213: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yaml_cfg = edict(yaml.load(f))
Caching xml list to data/cache/voc_db_train.pkl...
Traceback (most recent call last):
  File "train_eval.py", line 197, in <module>
    for x in ('train', 'test')}
  File "train_eval.py", line 197, in <dictcomp>
    for x in ('train', 'test')}
  File "/media/work/3D/PCA-GM/data/data_loader.py", line 19, in __init__
    self.ds = eval(self.name)(**args)
  File "/media/work/3D/PCA-GM/data/pascal_voc.py", line 117, in __init__
    self.filter_list()
  File "/media/work/3D/PCA-GM/data/pascal_voc.py", line 135, in filter_list
    assert xml_file.exists(), '{} does not exist.'.format(xml_file)
AssertionError: data/PascalVOC/VOC2011/annotations/2008_008467.xml does not exist.

```

The directory is as below:
![pac-gm](https://user-images.githubusercontent.com/16812362/65428172-81e73100-de46-11e9-933e-b1ec1c50d615.png)

**Comment by rogerwwww** [comment]
Hi, where did you download your VOC2011? The layout seems different from mine. Here's my layout of directory ``PascalVOC'':
```
├── annotations
│   ├── aeroplane
│   ├── bicycle
│   ├── bird
│   ├── boat
│   ├── bottle
│   ├── bus
│   ├── car
│   ├── cat
│   ├── chair
│   ├── cow
│   ├── diningtable
│   ├── dog
│   ├── horse
│   ├── motorbike
│   ├── person
│   ├── pottedplant
│   ├── sheep
│   ├── sofa
│   ├── train
│   └── tvmonitor
└── VOC2011
    ├── Annotations
    ├── ImageSets
    ├── JPEGImages
    ├── SegmentationClass
    └── SegmentationObject
```

**Comment by kxhit** [comment]
Hi! Thanks for your timely response! @rogerwwww 
I download the VOC2011 data from [here](http://host.robots.ox.ac.uk/pascal/VOC/voc2011/index.html#devkit) and the annotations from [here](https://www2.eecs.berkeley.edu/Research/Projects/CS/vision/shape/poselets/).
[tar1](http://host.robots.ox.ac.uk/pascal/VOC/voc2011/VOCtrainval_25-May-2011.tar)
[tar2](https://www2.eecs.berkeley.edu/Research/Projects/CS/vision/shape/poselets/voc2011_keypoints_Feb2012.tgz)

I'm not familiar with VOC2011 dataset. I wish to use the graph matching model in other domain. Please help me. Thanks a lot!

**Comment by rogerwwww** [comment]
Inside ``TrainVal``, you are going to find TrainVal/VOCdevkit/**VOC2011**. Place this VOC2011 under PascalVOC.

**Comment by kxhit** [comment]
![pca-gm2](https://user-images.githubusercontent.com/16812362/65480858-9b7b8d80-dec5-11e9-9fff-c0b5aa841a22.png)

Still getting error.

**Comment by rogerwwww** [comment]
That's weird. It should be under the VOC2011 directory.
I've just downloaded one and I found the following directories under VOC2011:
```Annotations  ImageSets  JPEGImages  SegmentationClass  SegmentationObject```
Could you please double-check?

**Comment by kxhit** [comment]
I made a stupid mistake. Now everything is OK. Sorry to bother you.
