### ISSUE TITLE
Some questions about code in feature_align.py

### ISSUE THREAD

**Issue by JiewenZhao** [Thinklab-SJTU/PCA-GM#11]
Hi, I have two questions about the code in feature_align.py.

- `step = ori_size / feat_size`
   `p = (p - step / 2) / ori_size * feat_size`
I'm confused about what the step means and the coordinate transforms.

- `Ia = im[:, y0, x0]`
I'm confused about the calculating method about the feature of the corresponding point.  Why y first and then x?

**Comment by rogerwwww** [comment]
Hi, the coordinate transform part works as follows:
* After several pooling layers in CNN, the size of feature map changes from original image size (256x256) to a smaller size (e.g. 32x32 for relu_4_2 and 16x16 for relu_5_1, in VGG16 net)
* The center of each pixel in the smaller feature map corresponds to a coordinate in the original image
* This correspondence is computed by the first two lines you listed

For second the question on coordinates:
Although hard to realize, the way we index images differs from the way we index tensors. To be more specific:
* Firstly, **tensors**  are indexed by ``t[row_index, col_index]``
* And images are usually indexed by ``x_coordinate`` and ``y_coordinate``. 
* However, if we treat ``t`` as an **image**, its index should be ``t[y_coordinate, x_coordinate]``. If we place the tensor on a plane, we will find out that the ``y_coordinates`` correspond to row numbers, and ``x_coordinates`` correspond to column numbers.

Therefore, ``y`` should be first then ``x``.

**Comment by 1368069096** [comment]
Hello, I also have a question about the code in feature_align.py. 
`interp_2d(feature, _P, ori_size, feat_size, out=F[idx, :, 0:n])`
I could not understand why the function 'interp_2d'  has no returns but the tensor F could be changed. 
In my view, I would write as follows. 
`F=interp_2d(feature, _P, ori_size, feat_size, out=F[idx, :, 0:n])`
Then the tensor F could be changed. 

I think that this may result from some proporties of pytorch (a parameter pass by address). However, I could not find what you write bring these proporties.

**Comment by rogerwwww** [comment]
Hi @1368069096 ,

both should work fine:
```
interp_2d(feature, _P, ori_size, feat_size, out=F[idx, :, 0:n])
```
and
```
F[idx, :, 0:n]=interp_2d(feature, _P, ori_size, feat_size)
```

We follow the common syntax in pytorch, as most pytorch functions support both ``A = foo(B)`` and ``foo(B, out=A)``
