### ISSUE TITLE
dummy node and non-correspondence node 

### ISSUE THREAD

**Issue by XuyangBai** [Thinklab-SJTU/PCA-GM#13]
Hi @rogerwwww  Thanks for your sharing. I am kind of confused about the code about `dummy_row` in the `SinkHorn` layer:
1. Are you assuming that there are exact one-to-one correspondences for each node in graph1? And is the dummy point added for the cases that node of graph1 is more than graph2?
2. I wonder how if some of the nodes in graph1 have no correspondence in graph2? e.g. the ground truth permutation matrix has shape [M, N] and the `i`th row are all zero. Is the network able to handle such situations?

**Comment by rogerwwww** [comment]
Hi Xuyang,

Sorry for the late reply, I seemed to have missed your message. 
In our ICCV paper we assume there are exact one-to-one correspondence, i.e. M=N. And ``dummy_row`` have no use in our ICCV experiment.
However, during further study we discovered that our methods are capable to handle the case when some of the nodes in graph1 have no correspondence in graph2, i.e. M≠N. You may experiment this by turning ``dummy_row=True``

**Comment by XuyangBai** [comment]
Nevermind : ) Thanks for your explanation.
