### ISSUE TITLE
您好，请问代码中从VGG网络中提取的edge_layers的作用是什么呢？

### ISSUE THREAD

**Issue by shaofengzeng** [Thinklab-SJTU/PCA-GM#14]
您好，看过您的论文后阅读您提供的代码，在文件utils/backbone.py中，分别提取node_layers, 和edge_layers. 虽然在实验部分提到“First-order and second-order features are extracted from shallower layer (relu4 2) and deeper layer (relu5 1) of VGG16, respectively. ” 但是看论文里，似乎PCA-GM实现里只需要提取顶点特征即可，不需要提取edge_layers

**Comment by rogerwwww** [comment]
Hi, this repository is designed with the peer paper "Deep learning of graph matching." 

As you mentioned, in PCA-GM only node features are adopted, therefore features from "node-layers" and "edge-layers" are concatenated. However, in "Deep learning of graph matching", "node-layers" build the node-to-node similarity and "edge-layers" build the edge-to-edge similarity. We keep these notations for the compatibility against "Deep learning of graph matching".

**Comment by shaofengzeng** [comment]
Thank you for your reply. This is the one of best work (both paper and code) i‘ve ever seen before.

**Comment by rogerwwww** [comment]
Thank you for your interest in our work! 😃
