### ISSUE TITLE
interp_2d函数和torch.nn.functional.grid_sample的区别

### ISSUE THREAD

**Issue by shaofengzeng** [Thinklab-SJTU/PCA-GM#16]
您好，请问，feature_align.py中interp_2d和pytorch的函数torch.nn.functional.grid_sample有区别吗？
torch.nn.functional.grid_sample也能通过插值算法实现对原图像特征点提取特征的功能，不知为何这里没有使用这一函数，还请指教哈~

**Comment by shaofengzeng** [comment]
经过测试，torch.nn.functional.grid_sample得到的结果有时候是0

**Comment by rogerwwww** [comment]
Thank you for your comments!
