### ISSUE TITLE
code failing with FileNotFoundError: [Errno 2] No such file or directory: 'output/vgg16_pca_willow/params/params_0020.pt'

### ISSUE THREAD

**Issue by HeddaCohenIndelman** [Thinklab-SJTU/PCA-GM#19]
Hello, 
I am trying to train on the Willow dataset (without pre-trained params on PASCAL).
I am running it by  python train_eval.py --cfg experiments/vgg16_pca_willow.yaml 

An error is produced: 
FileNotFoundError: [Errno 2] No such file or directory: 'output/vgg16_pca_willow/params/params_0020.pt'

Do I have to initialize these params before training?

Thank you,
Hedda.

**Comment by rogerwwww** [comment]
Hi Hedda,

Please see the detailed instructions to reproduce our Willow dataset result https://github.com/Thinklab-SJTU/PCA-GM#detailed-instructions-on-willow-object-class-dataset

**Comment by HeddaCohenIndelman** [comment]
Thank you, I was able to resolve it.
