### ISSUE TITLE
Paper related question: how do you determine the initial graph structure

### ISSUE THREAD

**Issue by chenbowen** [Thinklab-SJTU/PCA-GM#2]
This is possibly a naive question: after the feature extractor, how do you build the initial graph structure? I notice that according to Figure 1, each node is not connected to all other nodes. How do you determine the graph structure? 
Thanks.

**Comment by rogerwwww** [comment]
Hi, in PCA-GM they are constructed by Delaunay triangulation. Details of graph construction step for all peer methods can be found in Sec. 4.1 in our ICCV paper.
