### ISSUE TITLE
Loss Sudden increase and cannot decline

### ISSUE THREAD

**Issue by still-wait** [Thinklab-SJTU/PCA-GM#4]
commend：
```
python train_eval.py --cfg experiments/vgg16_pca_voc.yaml
```
The configuration file has not been modified.       

As the picture shows：
![image](https://user-images.githubusercontent.com/15628872/67350665-eef10200-f57d-11e9-9072-8d49e21ff6e2.png)

**Comment by rogerwwww** [comment]
Hi, what is the evaluation accuracy after epoch 6? If it is a moderately good accuracy, it should be fine. 
BTW we do not carefully tune the training parameters in the configuration file. If you just don't want to see the loss crash, perhaps you could change [this line](https://github.com/Thinklab-SJTU/PCA-GM/blob/master/experiments/vgg16_pca_voc.yaml#L34) to 
```yaml
NUM_EPOCHS: 7
```

**Comment by still-wait** [comment]
mean accuracy=0.634 after epoch 6.

**Comment by rogerwwww** [comment]
Got it, it could be (a little bit) better. Will update if we find a better config.
